dist: trusty
sudo: true

language: c

services:
  - docker

notifications:
  email: false

before_install:
  - git clone --recursive https://github.com/JumperXYZ/JumperTX.git /tmp/JumperTX
  
install:
  - cd ${TRAVIS_BUILD_DIR}
  - ls -al
  - docker build -t benlye/jumpertx-build .

script:
  - docker run --rm -it -v /tmp/JumperTX:/jumpertx benlye/jumpertx-build
  - ls -al /tmp/JumperTX/jumpertx-t16.bin
  - if [ ! -f /tmp/JumperTX/jumpertx-t16.bin ]; then
      exit 1;
    fi
