dist: trusty
sudo: true

language: c

services:
  - docker

notifications:
  email: false

before_install:
  - git clone --recursive https://github.com/JumperXYZ/JumperTX.git /tmp/JumperTX
  
install:
  - cd ${TRAVIS_BUILD_DIR}
  - ls -al
  - docker build -t benlye/jumpertx-build .

script:
  # Build for T16 with no extra cmake flags
  - echo -e "travis_fold:start:Param1\033[33;1mParam2\033[0m"
  - docker run --rm -it -v /tmp/JumperTX:/jumpertx benlye/jumpertx-build
  - echo -e "travis_fold:end:Param1"
