dist: trusty
sudo: true

language: c

services:
  - docker

notifications:
  email: false

before_install:
  - git clone --recursive https://github.com/JumperXYZ/JumperTX.git /tmp/JumperTX
  - start_fold() { echo -e "travis_fold:start:$1\033[33;1m$2\033[0m" }
  - end_fold() { echo -e "\ntravis_fold:end:$1\r" }
  
install:
  - cd ${TRAVIS_BUILD_DIR}
  - ls -al
  - docker build -t benlye/jumpertx-build .

script:
  # Build for T16 with no extra cmake flags
  - start_fold T16.defaults "Build for T16 with defaults"
  - docker run --rm -it -v /tmp/JumperTX:/jumpertx benlye/jumpertx-build
  - end_fold T16.defaults
