dist: trusty
sudo: true

language: c

services:
  - docker

notifications:
  email: false

before_install:
  - git clone --recursive https://github.com/JumperXYZ/JumperTX.git /tmp/JumperTX
  #- start_fold() { echo -e "travis_fold:start:$1\033[33;1m$2\033[0m"; }
  #- end_fold() { echo -e "\ntravis_fold:end:$1\r"; }
  
install:
  - cd ${TRAVIS_BUILD_DIR}
  - ls -al
  - docker build -t benlye/jumpertx-build .
  - start_fold() { echo -e "travis_fold:start:$1"; }
  - end_fold() { echo -e "\ntravis_fold:end:$1\r"; }
  - runBuild() { start_fold $1; travis_time_start; echo "docker run --rm -it -v /tmp/JumperTX:/jumpertx -e \"CMAKE_FLAGS=$2\" benlye/jumpertx-build"; docker run --rm -it -v /tmp/JumperTX:/jumpertx -e "CMAKE_FLAGS=$2" benlye/jumpertx-build; end_fold $1; }

before_script:
  - export -f travis_fold
  - export -f travis_nanoseconds
  - export -f travis_time_start
  - export -f travis_time_finish
  - chmod +x travis_tests.sh

script:
  #- ./travis_tests.sh
  - runBuild "T16.Default"
  - runBuild "T16.lang.German" "TRANSLATIONS=DE PCB=T12"
